os: linux
dist: focal
language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
    - libcups2-dev

branches:
  only:
  - develop

services:
- mysql

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls

before_script:
- flake8 edc_visit_tracking
- mysql -e 'create database edc character set utf8;'

script:
- coverage run --source=edc_visit_tracking manage.py test

after_success:
- coveralls

# notifications:
#   slack:
#     secure: CgGKonmu+F+g9UiV25ClG15h7AASrkfCj/IrEyWAu2xcgIWeiFI3P+wPnNvU+9gNemtS+NBcDk1X4+yEbF3DR+dp36R4SEUWza00yyFW1qaMrankeoud1NR5t/7U4NhCN904p5rdPhOmKbraf8L5eOFii8SUA3NFYJjBGE4ALGLdWtO88Ikitp8mtqF6YvtbeXMuB3RgDq0lxDmSnm70BrJhSXUmYEacVC367+35dxDK+Bzl2+7EcRAWBgFln25KSN7SG3WRgOGVrehTtpTvXnasyE8re00nwJZ05Og6QCRj7ka4pV0ezoTOweBkgLoDDWyRyv2tVlh780bDSOFMfYZLWkqrGqGseZMnuVmDiJmOpa57zyIxIV5Wl7gQXsgtdOtO6ccmYkqU8AnVm8LKd7l1PfKDt14dw0fT4AbuIQzj5KnJ64t6PQmUFCXNJU2Rh/jEKoO+FQeB43KR5dB6+7PrAAP7EALs1kKCBfA6VHr2vJA7FjrYlRwzniB9o3/9Gpx2fpUP1mbXFgxMFWL3lHm3TNfkHGDWTnMFMnqv/O+HIAYOcCJiJKdI03rC3c9BfLWwSxPCGGCvHWtbpTflqQnrE713MM+FFVGjGYHn4C+3x81D0Xqd0tEqFZ0QAF3TZgPhr13+otSD8fuNtoFOxMMj8Oiqrv14ZQq+eIkBmSI=
