# from edc_constants.constants import (OFF_STUDY)

COMPLETED_PROTOCOL_VISIT = 'completed protocol'
DEFERRED_VISIT = 'deferred'
LOST_VISIT = 'lost'
MISSED_VISIT = 'missed'
SCHEDULED = 'scheduled'
UNSCHEDULED = 'unscheduled'

NO_FOLLOW_UP_REASONS = [
    MISSED_VISIT, LOST_VISIT, DEFERRED_VISIT]
FOLLOW_UP_REASONS = [SCHEDULED, UNSCHEDULED, COMPLETED_PROTOCOL_VISIT]
REQUIRED_REASONS = NO_FOLLOW_UP_REASONS + FOLLOW_UP_REASONS

CHART = 'chart'
