VISIT_REASON_NO_FOLLOW_UP_CHOICES = ['missed', 'death', 'lost', 'deferred']
VISIT_REASON_FOLLOW_UP_CHOICES = ['scheduled', 'unscheduled', 'off study']
VISIT_REASON_REQUIRED_CHOICES = VISIT_REASON_FOLLOW_UP_CHOICES + VISIT_REASON_NO_FOLLOW_UP_CHOICES
