name: Checks

on:
  push:
    branches: [ "develop" ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]
        django-version: ['4.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pycups
        run: |
          sudo apt-get -y update
          sudo apt-get install -y libcups2-dev

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 Django coverage
          pip install coveralls codecov

      # - name: Create required directories and adjust permissions
      #   run: |
      #     sudo mkdir -p /etc/edc_visit_tracking
      #     sudo chown -R $USER:$USER /etc/edc_visit_tracking
      - name: Create directory for keys
        run: mkdir -p ~/crypto_fields
      - name: Set environment variable for key path
        run: echo "KEY_PATH=${HOME}/crypto_fields" >> $GITHUB_ENV

      - name: Run Flake8 Lint and Check
        run: |
          flake8

      - name: Run Tests
        run: |
          coverage run --source=edc_visit_tracking manage.py test
          coverage xml -i
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Report Coverage
        run: |
          coverage xml
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
